// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAliTwOWaoqsoVWgyMoFh3kjPI-Sp9Ncno',
    appId: '1:877115995554:web:dbcd3a7caa9056df26eefb',
    messagingSenderId: '877115995554',
    projectId: 'flutter-projects-bb11d',
    authDomain: 'flutter-projects-bb11d.firebaseapp.com',
    storageBucket: 'flutter-projects-bb11d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu4_MXdYrlH2tur_Kekeaafzuc6Sis28E',
    appId: '1:877115995554:android:ebbef609ba8aa36626eefb',
    messagingSenderId: '877115995554',
    projectId: 'flutter-projects-bb11d',
    storageBucket: 'flutter-projects-bb11d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXzEnUf8WbXgKLBpQO9P1BG3JIHjxR-gI',
    appId: '1:877115995554:ios:6b7c95c22a5427d026eefb',
    messagingSenderId: '877115995554',
    projectId: 'flutter-projects-bb11d',
    storageBucket: 'flutter-projects-bb11d.firebasestorage.app',
    iosBundleId: 'com.manuelaviola.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXzEnUf8WbXgKLBpQO9P1BG3JIHjxR-gI',
    appId: '1:877115995554:ios:63a3d0c57e88a7df26eefb',
    messagingSenderId: '877115995554',
    projectId: 'flutter-projects-bb11d',
    storageBucket: 'flutter-projects-bb11d.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );
}
